# ─────────────────────────────────────────────
#  pg_hba.conf  —  PRIMARY node
#  Controls authentication for incoming connections
# ─────────────────────────────────────────────

# TYPE   DATABASE        USER            ADDRESS         METHOD

# Local connections (inside the container)
local   all             all                             trust

# Allow the app user to connect from anywhere on the Docker network
host    mrs_db          mrs_user        0.0.0.0/0       md5

# Allow standbys to connect for streaming replication
# (the 'replication' keyword is special — it's not a real DB name)
host    replication     replicator      0.0.0.0/0       md5